In [15]:
import pandas as pd

In [16]:
raw_data_df = pd.read_csv("../src/assets/comment-intent/v3/raw_data/raw_data.csv")
raw_data_df["comment_length"] = raw_data_df["comment_text"].astype(str).str.len()
raw_data_df

,comment_id,comment_text,published_at,source,language,comment_length
0,24,Thanks for the video tutorial,2024-10-23 10:51:22+00:00,NaN,NaN,29
1,23,How to cancel my send money to Philippines?,2024-12-31 07:07:47+00:00,NaN,NaN,43
2,22,Under review problem,2025-03-08 06:49:48+00:00,NaN,NaN,20
3,21,Why there is showing invalid input,2025-04-07 12:38:54+00:00,NaN,NaN,34
4,19,Under review problem,2025-06-18 20:43:23+00:00,NaN,NaN,20
5,18,Verification call not received,2025-06-20 06:31:35+00:00,NaN,NaN,30
6,17,International transfer option no showing whats...,2025-07-02 13:42:13+00:00,NaN,NaN,59
7,15,Bhai first time money trsfar me Kitna time lag...,2025-09-01 05:47:22+00:00,NaN,NaN,51
8,13,International transfer in progress,2025-09-02 22:58:40+00:00,NaN,NaN,34
9,12,It doesn&#39;t work. Just notification warning...,2025-09-03 09:13:24+00:00,NaN,NaN,67
10,11,What problem no showing international transfer?,2025-09-10 02:22:03+00:00,NaN,NaN,47
11,10,Bhai Kitna time lgta hai transfer hone me,2025-10-20 12:23:15+00:00,NaN,NaN,41
12,9,Kya Nepal se india bej sakte h pase,2025-11-14 15:22:24+00:00,NaN,NaN,35
13,8,Why international pay 98 ksa,2025-12-02 10:20:29+00:00,NaN,NaN,28
14,7,What if the beneficiary has a single name on t...,2025-12-10 16:47:37+00:00,NaN,NaN,171
15,6,Why my verification is pending,2025-12-27 23:35:43+00:00,NaN,NaN,30
16,5,My beneficiary was rejected. And I can&#39;t s...,2026-01-10 00:57:16+00:00,NaN,NaN,72
17,4,খুব সহজ একটা এপস ৫ মিনিটে দেশে টাকা পাঠালাম🥰🥰আ...,2026-01-10 16:00:17+00:00,NaN,NaN,86
18,2,Am send money india. Not go why,2026-04-01 09:35:05+00:00,NaN,NaN,31
19,1,Barq account is its not same another bank very...,2026-04-01 18:44:21+00:00,NaN,NaN,175

In [17]:
raw_data_df.shape

(20, 6)

In [18]:
clean_data_df = pd.read_csv("../src/assets/comment-intent/v3/processed_data/clean_data.csv")
clean_data_df["comment_length"] = clean_data_df["comment"].astype(str).str.len()
clean_data_df

,comment_id,comment,published_at,source,language,comment_length
0,24,Thanks for the video tutorial,2024-10-23 10:51:22+00:00,NaN,NaN,29
1,23,How to cancel my send money to Philippines?,2024-12-31 07:07:47+00:00,NaN,NaN,43
2,22,Under review problem,2025-03-08 06:49:48+00:00,NaN,NaN,20
3,21,Why there is showing invalid input,2025-04-07 12:38:54+00:00,NaN,NaN,34
4,18,Verification call not received,2025-06-20 06:31:35+00:00,NaN,NaN,30
5,17,International transfer option no showing whats...,2025-07-02 13:42:13+00:00,NaN,NaN,59
6,15,Bhai first time money trsfar me Kitna time lag...,2025-09-01 05:47:22+00:00,NaN,NaN,51
7,13,International transfer in progress,2025-09-02 22:58:40+00:00,NaN,NaN,34
8,12,It doesn&#39;t work. Just notification warning...,2025-09-03 09:13:24+00:00,NaN,NaN,67
9,11,What problem no showing international transfer?,2025-09-10 02:22:03+00:00,NaN,NaN,47
10,10,Bhai Kitna time lgta hai transfer hone me,2025-10-20 12:23:15+00:00,NaN,NaN,41
11,9,Kya Nepal se india bej sakte h pase,2025-11-14 15:22:24+00:00,NaN,NaN,35
12,8,Why international pay 98 ksa,2025-12-02 10:20:29+00:00,NaN,NaN,28
13,7,What if the beneficiary has a single name on t...,2025-12-10 16:47:37+00:00,NaN,NaN,171
14,6,Why my verification is pending,2025-12-27 23:35:43+00:00,NaN,NaN,30
15,5,My beneficiary was rejected. And I can&#39;t s...,2026-01-10 00:57:16+00:00,NaN,NaN,72
16,4,খুব সহজ একটা এপস ৫ মিনিটে দেশে টাকা পাঠালাম🥰🥰আ...,2026-01-10 16:00:17+00:00,NaN,NaN,86
17,2,Am send money india. Not go why,2026-04-01 09:35:05+00:00,NaN,NaN,31
18,1,Barq account is its not same another bank very...,2026-04-01 18:44:21+00:00,NaN,NaN,175

In [19]:
clean_data_df.shape

(19, 6)

In [20]:
label_data_df = pd.read_csv("../src/assets/comment-intent/v3/processed_data/label_data.csv")
label_data_df

,comment,intent,source,confidence,latency_ms,cost_usd,stage
0,Thanks for the video tutorial,Praise,gpt-4o-mini,1.0,3669.07,0.000024,training
1,How to cancel my send money to Philippines?,Question,gpt-4o-mini,1.0,729.19,0.000024,training
2,Under review problem,Complaint,gpt-4o-mini,1.0,1029.16,0.000024,training
3,Why there is showing invalid input,Question,gpt-4o-mini,1.0,708.41,0.000024,training
4,Verification call not received,Complaint,gpt-4o-mini,1.0,1332.40,0.000024,training
5,International transfer option no showing whats...,Question,gpt-4o-mini,1.0,1023.81,0.000024,training
6,Bhai first time money trsfar me Kitna time lag...,Question,gpt-4o-mini,1.0,821.58,0.000025,training
7,International transfer in progress,Statement,gpt-4o-mini,1.0,918.78,0.000024,training
8,It doesn&#39;t work. Just notification warning...,Complaint,gpt-4o-mini,1.0,723.95,0.000025,training
9,What problem no showing international transfer?,Question,gpt-4o-mini,1.0,1454.63,0.000024,training
10,Bhai Kitna time lgta hai transfer hone me,Question,gpt-4o-mini,1.0,892.99,0.000025,training
11,Kya Nepal se india bej sakte h pase,Question,gpt-4o-mini,1.0,631.88,0.000025,training
12,Why international pay 98 ksa,Question,gpt-4o-mini,1.0,1230.63,0.000024,training
13,What if the beneficiary has a single name on t...,Question,gpt-4o-mini,1.0,878.11,0.000029,training
14,Why my verification is pending,Question,gpt-4o-mini,1.0,2128.42,0.000024,training
15,My beneficiary was rejected. And I can&#39;t s...,Question,gpt-4o-mini,1.0,822.27,0.000026,training
16,খুব সহজ একটা এপস ৫ মিনিটে দেশে টাকা পাঠালাম🥰🥰আ...,Praise,gpt-4o-mini,1.0,965.91,0.000031,training
17,Am send money india. Not go why,Question,gpt-4o-mini,1.0,1380.52,0.000024,training
18,Barq account is its not same another bank very...,Complaint,gpt-4o-mini,1.0,611.82,0.000029,training

In [21]:
transform_data_df = pd.read_csv("../src/assets/comment-intent/v3/processed_data/data_transformation.csv")
transform_data_df

,system,instruction,input,output,history,intent
0,You are an NLP data parser specialized in text...,## YouTube Comment:\nThanks for the video tuto...,NaN,"{""predicted_intent"": ""Praise""}",[],Praise
1,You are an NLP data parser specialized in text...,## YouTube Comment:\nHow to cancel my send mon...,NaN,"{""predicted_intent"": ""Question""}",[],Question
2,You are an NLP data parser specialized in text...,## YouTube Comment:\nUnder review problem\n\n#...,NaN,"{""predicted_intent"": ""Complaint""}",[],Complaint
3,You are an NLP data parser specialized in text...,## YouTube Comment:\nWhy there is showing inva...,NaN,"{""predicted_intent"": ""Question""}",[],Question
4,You are an NLP data parser specialized in text...,## YouTube Comment:\nVerification call not rec...,NaN,"{""predicted_intent"": ""Complaint""}",[],Complaint
5,You are an NLP data parser specialized in text...,## YouTube Comment:\nInternational transfer op...,NaN,"{""predicted_intent"": ""Question""}",[],Question
6,You are an NLP data parser specialized in text...,## YouTube Comment:\nBhai first time money trs...,NaN,"{""predicted_intent"": ""Question""}",[],Question
7,You are an NLP data parser specialized in text...,## YouTube Comment:\nInternational transfer in...,NaN,"{""predicted_intent"": ""Statement""}",[],Statement
8,You are an NLP data parser specialized in text...,## YouTube Comment:\nIt doesn&#39;t work. Just...,NaN,"{""predicted_intent"": ""Complaint""}",[],Complaint
9,You are an NLP data parser specialized in text...,## YouTube Comment:\nWhat problem no showing i...,NaN,"{""predicted_intent"": ""Question""}",[],Question
10,You are an NLP data parser specialized in text...,## YouTube Comment:\nBhai Kitna time lgta hai ...,NaN,"{""predicted_intent"": ""Question""}",[],Question
11,You are an NLP data parser specialized in text...,## YouTube Comment:\nKya Nepal se india bej sa...,NaN,"{""predicted_intent"": ""Question""}",[],Question
12,You are an NLP data parser specialized in text...,## YouTube Comment:\nWhy international pay 98 ...,NaN,"{""predicted_intent"": ""Question""}",[],Question
13,You are an NLP data parser specialized in text...,## YouTube Comment:\nWhat if the beneficiary h...,NaN,"{""predicted_intent"": ""Question""}",[],Question
14,You are an NLP data parser specialized in text...,## YouTube Comment:\nWhy my verification is pe...,NaN,"{""predicted_intent"": ""Question""}",[],Question
15,You are an NLP data parser specialized in text...,## YouTube Comment:\nMy beneficiary was reject...,NaN,"{""predicted_intent"": ""Question""}",[],Question
16,You are an NLP data parser specialized in text...,## YouTube Comment:\nখুব সহজ একটা এপস ৫ মিনিটে...,NaN,"{""predicted_intent"": ""Praise""}",[],Praise
17,You are an NLP data parser specialized in text...,## YouTube Comment:\nAm send money india. Not ...,NaN,"{""predicted_intent"": ""Question""}",[],Question
18,You are an NLP data parser specialized in text...,## YouTube Comment:\nBarq account is its not s...,NaN,"{""predicted_intent"": ""Complaint""}",[],Complaint