In [57]:
import pandas as pd

In [58]:
version = "v1"

In [59]:
raw_data_df = pd.read_csv(f"../src/assets/comment-intent/{version}/raw_data/raw_data.csv")
raw_data_df["comment_length"] = raw_data_df["comment_text"].astype(str).str.len()
raw_data_df

,comment_id,comment_text,published_at,comment_length
0,caabdf91-445b-415c-9afa-8837f1679b79,لارابط ولا اسم ولا صورة ولاشيء,2024-07-31 23:21:36+00:00,30
1,71da5917-ae5d-4085-8eeb-ad79d271c3c6,كودي 6D5A0497DEGCR شغال 100% برق جربته أنا وا ...,2024-08-01 23:19:05+00:00,69
2,51618b22-ea4b-42ef-a78d-486448dddda9,CF00EFD9C2GCR كودي اللي يبي يلعب معي ويكسب,2024-08-02 02:32:16+00:00,43
3,9fc91184-00fa-461f-8be4-54d19a6bad87,كودي <br>D89FCB27C9GCR<br>اللهم ارزقني وارزق مني,2024-08-03 05:34:56+00:00,48
4,3a97b51f-e977-4895-9a3b-71968457acfe,اخوي شاركت الكود لا اكثر من شخصين ولا جتني محا...,2024-08-10 20:13:28+00:00,61
...,...,...,...,...
1020,869cef70-6ae4-4a15-a482-d3940a16c7da,أخي الفاضل حاولت أسحب ٥٠ ريال من ماكينه الأهلي...,2026-05-09 10:40:57+00:00,82
1021,221e747a-ea7a-40c1-8a8e-d7d32e6af0de,ماذا يستفيد صناع التطبيق من بطاقة برق؟ ما زال ...,2026-05-11 14:44:29+00:00,55
1022,96a84d78-2f90-4b6a-8407-fde585fc879d,كيف يعني جوائز بمليون ريال؟,2026-05-12 06:09:46+00:00,27
1023,348529bd-fa97-4206-b09a-77fd8120fe56,كم خد التحويل اليومى او الشهري,2026-05-14 12:04:45+00:00,30
1024,7d6c661e-c270-41e7-b7e4-b17aae6c66ab,انا عندي مشكلة وهي انا طلبت بطاقتين برق مدى وف...,2026-05-16 15:37:44+00:00,160

In [60]:
raw_data_df["published_at"].isna().sum()
raw_data_df["published_at"].min()
raw_data_df["published_at"].max()

'2026-05-16 15:37:44+00:00'

In [61]:
raw_data_df.shape

(1025, 4)

In [62]:
clean_data_df = pd.read_csv(f"../src/assets/comment-intent/{version}/processed_data/clean_data.csv")
clean_data_df["comment_length"] = clean_data_df["comment"].astype(str).str.len()
clean_data_df

,comment_id,comment,published_at,comment_length
0,caabdf91-445b-415c-9afa-8837f1679b79,لارابط ولا اسم ولا صورة ولاشيء,2024-07-31 23:21:36+00:00,30
1,71da5917-ae5d-4085-8eeb-ad79d271c3c6,كودي 6D5A0497DEGCR شغال 100% برق جربته أنا وا ...,2024-08-01 23:19:05+00:00,69
2,51618b22-ea4b-42ef-a78d-486448dddda9,CF00EFD9C2GCR كودي اللي يبي يلعب معي ويكسب,2024-08-02 02:32:16+00:00,43
3,9fc91184-00fa-461f-8be4-54d19a6bad87,كودي <br>D89FCB27C9GCR<br>اللهم ارزقني وارزق مني,2024-08-03 05:34:56+00:00,48
4,3a97b51f-e977-4895-9a3b-71968457acfe,اخوي شاركت الكود لا اكثر من شخصين ولا جتني محا...,2024-08-10 20:13:28+00:00,61
...,...,...,...,...
1008,869cef70-6ae4-4a15-a482-d3940a16c7da,أخي الفاضل حاولت أسحب ٥٠ ريال من ماكينه الأهلي...,2026-05-09 10:40:57+00:00,82
1009,221e747a-ea7a-40c1-8a8e-d7d32e6af0de,ماذا يستفيد صناع التطبيق من بطاقة برق؟ ما زال ...,2026-05-11 14:44:29+00:00,55
1010,96a84d78-2f90-4b6a-8407-fde585fc879d,كيف يعني جوائز بمليون ريال؟,2026-05-12 06:09:46+00:00,27
1011,348529bd-fa97-4206-b09a-77fd8120fe56,كم خد التحويل اليومى او الشهري,2026-05-14 12:04:45+00:00,30
1012,7d6c661e-c270-41e7-b7e4-b17aae6c66ab,انا عندي مشكلة وهي انا طلبت بطاقتين برق مدى وف...,2026-05-16 15:37:44+00:00,160

In [63]:
clean_data_df.shape

(1013, 4)

In [64]:
label_data_df = pd.read_csv(f"../src/assets/comment-intent/{version}/processed_data/label_data.csv")
label_data_df

,comment_id,comment,intent,source,confidence,latency_ms,cost_usd,stage
0,caabdf91-445b-415c-9afa-8837f1679b79,لارابط ولا اسم ولا صورة ولاشيء,Complaint,gpt-4o-mini,1.0,4503.85,0.000025,training
1,71da5917-ae5d-4085-8eeb-ad79d271c3c6,كودي 6D5A0497DEGCR شغال 100% برق جربته أنا وا ...,Statement,gpt-4o-mini,1.0,2224.73,0.000031,training
2,51618b22-ea4b-42ef-a78d-486448dddda9,CF00EFD9C2GCR كودي اللي يبي يلعب معي ويكسب,Statement,gpt-4o-mini,1.0,1993.03,0.000026,training
3,9fc91184-00fa-461f-8be4-54d19a6bad87,كودي <br>D89FCB27C9GCR<br>اللهم ارزقني وارزق مني,Statement,gpt-4o-mini,1.0,525.87,0.000027,training
4,3a97b51f-e977-4895-9a3b-71968457acfe,اخوي شاركت الكود لا اكثر من شخصين ولا جتني محا...,Question,gpt-4o-mini,1.0,1103.37,0.000026,training
...,...,...,...,...,...,...,...,...
1008,869cef70-6ae4-4a15-a482-d3940a16c7da,أخي الفاضل حاولت أسحب ٥٠ ريال من ماكينه الأهلي...,Complaint,gpt-4o-mini,1.0,755.74,0.000027,training
1009,221e747a-ea7a-40c1-8a8e-d7d32e6af0de,ماذا يستفيد صناع التطبيق من بطاقة برق؟ ما زال ...,Question,gpt-4o-mini,1.0,789.09,0.000026,training
1010,96a84d78-2f90-4b6a-8407-fde585fc879d,كيف يعني جوائز بمليون ريال؟,Question,gpt-4o-mini,1.0,823.40,0.000024,training
1011,348529bd-fa97-4206-b09a-77fd8120fe56,كم خد التحويل اليومى او الشهري,Question,gpt-4o-mini,1.0,608.01,0.000025,training
1012,7d6c661e-c270-41e7-b7e4-b17aae6c66ab,انا عندي مشكلة وهي انا طلبت بطاقتين برق مدى وف...,Question,gpt-4o-mini,1.0,811.46,0.000030,training

In [65]:
transform_data_df = pd.read_csv(f"../src/assets/comment-intent/{version}/processed_data/data_transformation.csv")
transform_data_df

,system,instruction,input,output,history,intent
0,You are a strict text classification system.\n...,Comment:\nلارابط ولا اسم ولا صورة ولاشيء,NaN,"{""predicted_intent"": ""Complaint""}",[],Complaint
1,You are a strict text classification system.\n...,Comment:\nكودي 6D5A0497DEGCR شغال 100% برق جرب...,NaN,"{""predicted_intent"": ""Statement""}",[],Statement
2,You are a strict text classification system.\n...,Comment:\nCF00EFD9C2GCR كودي اللي يبي يلعب مع...,NaN,"{""predicted_intent"": ""Statement""}",[],Statement
3,You are a strict text classification system.\n...,Comment:\nكودي <br>D89FCB27C9GCR<br>اللهم ارزق...,NaN,"{""predicted_intent"": ""Statement""}",[],Statement
4,You are a strict text classification system.\n...,Comment:\nاخوي شاركت الكود لا اكثر من شخصين ول...,NaN,"{""predicted_intent"": ""Question""}",[],Question
...,...,...,...,...,...,...
1005,You are a strict text classification system.\n...,Comment:\nأخي الفاضل حاولت أسحب ٥٠ ريال من ماك...,NaN,"{""predicted_intent"": ""Complaint""}",[],Complaint
1006,You are a strict text classification system.\n...,Comment:\nماذا يستفيد صناع التطبيق من بطاقة بر...,NaN,"{""predicted_intent"": ""Question""}",[],Question
1007,You are a strict text classification system.\n...,Comment:\nكيف يعني جوائز بمليون ريال؟,NaN,"{""predicted_intent"": ""Question""}",[],Question
1008,You are a strict text classification system.\n...,Comment:\nكم خد التحويل اليومى او الشهري,NaN,"{""predicted_intent"": ""Question""}",[],Question
1009,You are a strict text classification system.\n...,Comment:\nانا عندي مشكلة وهي انا طلبت بطاقتين ...,NaN,"{""predicted_intent"": ""Question""}",[],Question